version: '2'
services:
  mysql: #服務名稱（不是容器名,名稱最好不要含有特殊字符，碰到過用下劃線時運行出錯）
    image: mysql:8.0.21
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d/"
    networks: #加入指定網絡
      - xxl_job
  xxljob01:
    image: docker.io/xuxueli/xxl-job-admin:2.2.0
    container_name: xxljob01
    ports:
      - "8081:8080"
    environment:
      PARAMS: '--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?Unicode=true&characterEncoding=UTF-8 --spring.datasource.username=root  --spring.datasource.password=root'
    networks:
      - xxl_job
    depends_on:
      - mysql
networks:
  xxl_job:
    driver: bridge