version: '3'
services:
  mysql:
    image: mysql:8.0.21
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root #root管理員使用者密碼
      MYSQL_USER: test   #建立test使用者
      MYSQL_PASSWORD: test  #設定test使用者的密碼
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  xxljob01:
    image: docker.io/xuxueli/xxl-job-admin:2.2.0
    container_name: xxljob01
    ports:
      - "8081:8080"
    environment:
      PARAMS: '--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?Unicode=true&characterEncoding=UTF-8 --spring.datasource.username=root  --spring.datasource.password=root'
    depends_on:
      - mysql
